LifeSG/validation-schema-generator

- src/__tests__/schema-generator/json-to-schema.spec.ts
- src/fields/generate-field-configs.ts
- src/fields/index.ts
- src/fields/numeric.ts
- src/fields/text.ts
- src/fields/types.ts
- src/file.ts
- src/index.ts
- src/schema-generator/index.ts
- src/schema-generator/json-to-schema.ts
- src/schema-generator/types.ts
- src/utils/index.ts
- src/utils/test-helper.ts
- MOL-12039
- this PR is to be reviewed after https://github.com/LifeSG/validation-schema-generator/pull/1
- contains basic implementation of JSON to Yup conversion
- created field config generator for `numeric` and `text` field
- added unit tests to jsonToSchema functions
> Json to yup logic

- src/__tests__/custom-rules/custom-rules.spec.ts
- src/__tests__/schema-generator/json-to-schema.spec.ts
- src/custom-rules/index.ts
- src/custom-rules/uinfin.ts
- src/custom-rules/values.ts
- src/index.ts
- src/schema-generator/json-to-schema.ts
- src/schema-generator/types.ts
- this PR is to be reviewed after https://github.com/LifeSG/validation-schema-generator/pull/2
- added `addRule()` function to allow defining custom rules
- added custom rules
- filled
- empty
- equals
- notEquals
- uinfin
> Custom validation

- src/__tests__/fields/date.spec.ts
- src/fields/date/date.ts
- src/fields/date/types.ts
- src/shared/error-messages.ts
- MOL-12343
- Added min / max date validation to date-input field
- Made corresponding update in frontend-engine: https://github.com/LifeSG/web-frontend-engine/pull/36
> [DATEVAL][WL] add min / max date validation rules

- package-lock.json
- package.json
- bump to v1.0.0-alpha.2
- changelog: https://github.com/LifeSG/validation-schema-generator/wiki/Changelog
> [MISC][WL] v1.0.0.alpha.2

- src/__tests__/custom-rules/custom-rules.spec.ts
- src/__tests__/fields/checkbox.spec.ts
- src/__tests__/fields/chips.spec.ts
- src/__tests__/fields/contact.spec.ts
- src/__tests__/fields/date.spec.ts
- src/__tests__/fields/email.spec.ts
- src/__tests__/fields/multi-select.spec.ts
- src/__tests__/fields/numeric.spec.ts
- src/__tests__/fields/radio.spec.ts
- src/__tests__/fields/select.spec.ts
- src/__tests__/fields/text.spec.ts
- src/__tests__/fields/textarea.spec.ts
- src/__tests__/fields/time.spec.ts
- src/__tests__/schema-generator/json-to-schema.spec.ts
- src/fields/generate-field-configs.ts
- src/schema-generator/types.ts
- merge to long-lived branch
- ready to merge
- delete branch
- replace `fieldType` with `uiType`
> fieldType -> uiType

- .github/pull_request_template.md
- README.md
- src/__tests__/schema-generator/json-to-schema.spec.ts
- src/fields/generate-field-configs.ts
- src/schema-generator/types.ts
- ready to merge to long-live branch
- delete branch
- added support for `referenceKey`
- updated docs to reflect new JSON structure
> referenceKey and docs

- src/schema-generator/types.ts
Changes
Added reset field into uiType list
[delete] branch
> [RESET-BUTTON] added reset to uiType list

- src/__tests__/fields/unit-number-field.spec.ts
- src/fields/generate-field-configs.ts
- src/fields/index.ts
- src/fields/unit-number-field.ts
- src/schema-generator/types.ts
- src/shared/error-messages.ts
**Changes**
Unit Number Field Validation
-   You may refer to this [BOOKINGSG-4079](https://jira.ship.gov.sg/browse/BOOKINGSG-4079)
> [BOOKINGSG-4079][AS] Unit Number Field Validation

- package-lock.json
- package.json
**Changes**
- v1.0.0-alpha.4 release
- Regenerated package-lock to resolve yaml vulnerability
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog
> Release/v1.0.0 alpha.4

- package-lock.json
- package.json
- src/__tests__/fields/image-upload.spec.ts
- src/fields/generate-field-configs.ts
- src/fields/image-upload.ts
- src/fields/index.ts
- src/schema-generator/types.ts
- src/shared/error-messages.ts
- src/utils/file-helper.ts
- src/utils/image-helper.ts
- src/utils/index.ts
- src/utils/test-helper.ts
**Changes**
- add support for image-upload field
- delete branch
- Add `image-upload` field
> Image upload

- src/__tests__/fields/switch.spec.ts
- src/fields/generate-field-configs.ts
- src/fields/index.ts
- src/fields/switch.ts
- src/schema-generator/types.ts
**Changes**
- Added switch field component
-   delete branch
-   You may refer to this [RBS-344](https://jira.ship.gov.sg/browse/RBS-344)
> Add Switch field component

- .github/workflows/README.md
- .github/workflows/trigger-gitlab-pipeline.yml
- .gitignore
- .prettierrc
- jest/jest.config.js
- package-lock.json
- package.json
- scripts/post-build.js
**Changes**
Prepare library for gitlab pipeline 
- Add gitlab pipeline trigger workflow
- Added junit report for tests
- Added post build script to copy package.json and Readme after npm build
> Creating Gitlab pipeline

- package-lock.json
- package.json
**Changes**
- Bump to alpha.5
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v100-alpha12-draft
> [MISC][WL] 1.0.0-alpha.5

- package-lock.json
- src/__tests__/fields/date-field.spec.ts
- src/fields/date-field/date-field.ts
- src/fields/date-field/types.ts
- src/shared/error-messages.ts
**Changes**
- Support design-system v2 upgrade change in frontend engine
- Date field
- Added support for excludedDates validation rule to disable specific dates
- Fixes for semver and word-wrap vulnerabilities
> Design system v2

- package-lock.json
- package.json
**Changes**
- Bump to v1.0.0-alpha.6
- Changelog: https://github.com/LifeSG/validation-schema-generator/wiki/Changelog#v100-alpha6-draft
> [MISC][WL] v1.0.0-alpha.6

- src/__tests__/fields/date-range-field.spec.ts
- src/fields/date-range-field/date-range-field.ts
- src/fields/date-range-field/index.ts
- src/fields/date-range-field/types.ts
- src/fields/generate-field-configs.ts
- src/schema-generator/types.ts
- src/shared/error-messages.ts
- src/utils/date-time-helper.ts
**Changes**
- Add validations and schema for date-range field
-   delete branch
-   You may refer to this ticket [RBS-427](https://jira.ship.gov.sg/browse/RBS-427)
> [RBS-427][VM] Add validations and schema for date-range field

- package-lock.json
- src/__tests__/fields/nested-multi-select.spec.ts
- src/fields/generate-field-configs.ts
- src/fields/index.ts
- src/fields/nested-multi-select.ts
- src/fields/nested-multi-select/index.ts
- src/fields/nested-multi-select/nested-multi-select.ts
- src/fields/nested-multi-select/types.ts
- src/schema-generator/types.ts
**Changes**
Added new validation and schema for nested-multi-select
Fixed critical vulnerability
-   You may refer to [RBS-952](https://jira.ship.gov.sg/browse/RBS-952)
> [RBS-952] validation and schema for nested-multi-select

- src/__tests__/fields/contact-field.spec.ts
- src/__tests__/fields/date-range-field.spec.ts
- src/fields/contact-field/contact-field.ts
- src/fields/date-range-field/date-range-field.ts
- src/schema-generator/types.ts
- src/shared/error-messages.ts
**Changes**
- Match changes in frontend engine
- Add `divider` and `grid` uiType
- Skip contact field international validation if it is not specified
- Add notPast and notFuture validation to date range
> Misc updates

- src/fields/generate-field-configs.ts
- src/schema-generator/types.ts
**Changes**
- Ensure validation config of fields nested within grid are validated as well
> [GRID][WL] support validation config nested within grid uiType

- src/__tests__/fields/masked-field.spec.ts
- src/fields/generate-field-configs.ts
- src/fields/index.ts
- src/fields/masked-field.ts
- src/schema-generator/types.ts
**Changes**
- support new uiType `masked-field` from FEE
- validation is identical to text-field and textarea as the masking is visual only
- New uiType `masked-field`
> Add masked-field uiType

- src/__tests__/fields/checkbox.spec.ts
- src/__tests__/fields/radio.spec.ts
- src/fields/checkbox.ts
- src/fields/generate-field-configs.ts
- src/fields/radio.ts
- src/schema-generator/conditional-render.ts
**Changes**
- Support children in checkbox and radio
- Should skip validation for fields that are conditionally rendered
> Support nested fields in checkbox and radio options

- src/__tests__/fields/file-upload.spec.ts
- src/__tests__/fields/image-upload.spec.ts
- src/fields/file-upload.ts
- src/fields/generate-field-configs.ts
- src/fields/image-upload.ts
- src/fields/index.ts
- src/schema-generator/types.ts
- src/shared/error-messages.ts
- src/utils/file-helper.ts
**Changes**
- Add support for file upload field
> File upload

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/validation-schema-generator/wiki/Changelog#v110-draft
> [MISC][WL] v1.1.0

- src/__tests__/custom-rules/custom-rules.spec.ts
- src/utils/value-helper.ts
**Changes**
Fixes invalid field key error when field is conditionally rendered based on a `switch` field
> Support conditional rendering based on boolean field

- package-lock.json
- package.json
**Changes**
- Change log: https://github.com/LifeSG/validation-schema-generator/wiki/Changelog#v111-draft
> [MISC][WL] v1.1.1

- package-lock.json
- package.json
**Changes**
- Changelog https://github.com/LifeSG/validation-schema-generator/wiki/Changelog#v112-draft
> [MISC][WL] v1.1.2

- src/__tests__/fields/e-signature-field.spec.ts
- src/__tests__/fields/range-select.spec.ts
- src/fields/e-signature-field.ts
- src/fields/generate-field-configs.ts
- src/fields/index.ts
- src/fields/range-select.ts
- src/schema-generator/types.ts
**Changes**
- add e-signature-field
- add range-select
- add support for accordion
- delete branch
> Add components

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/validation-schema-generator/wiki/Changelog#v120
> [MISC][WL] v1.2.0

- src/__tests__/fields/hidden-field.spec.ts
- src/fields/generate-field-configs.ts
- src/fields/hidden-field.ts
- src/fields/index.ts
- src/schema-generator/types.ts
**Changes**
- add support for `hidden-field`
> add support for hidden field

- .github/workflows/CODEOWNERS
- .github/workflows/trigger-gitlab-pipeline.yml
**Changes**
Description of changes...
-   [keep | delete] branch
-   [BREAKING | WARNING | remove if none] Description of change
-   You may refer to this [ticket](url)
-   Any other information you would like to include
> [MOL-15577][BC] Add codeowners

- src/__tests__/fields/array-field.spec.ts
- src/fields/array-field.ts
- src/fields/generate-field-configs.ts
- src/fields/index.ts
- src/schema-generator/types.ts
- src/shared/error-messages.ts
**Changes**
- Add `array-field` validation to match FEE component
- Additional check applied for `required` rule
- `min`, `max`, and `length` rules are already built into `Yup.array`
-   Support new `array-field` component
> Support `array-field` component

- src/__tests__/custom-rules/custom-rules.spec.ts
- src/__tests__/fields/date-field.spec.ts
- src/__tests__/schema-generator/json-to-schema.spec.ts
- src/custom-rules/apply-custom-rules.ts
- src/custom-rules/values.ts
- src/fields/date-field/date-field.ts
- src/fields/date-field/types.ts
- src/fields/date-range-field/date-range-field.ts
- src/schema-generator/types.ts
- src/shared/error-messages.ts
- src/utils/date-time-helper.ts
- src/utils/index.ts
**Changes**
Use case: Render alert if date selected is x days more / less than today's date
Requirements
- Add condition to date-field
- 
- Disable days that are out of range of the days specified
- 
- Add as a general conditional rendering rule
-   [keep | delete] branch
-   [BREAKING | WARNING | remove if none] Description of change
-   You may refer to this [CCUBE-1615](https://sgtechstack.atlassian.net/browse/CCUBE-1615)
-   Any other information you would like to include
> Ccube 1615

- src/__tests__/fields/date-field.spec.ts
- src/__tests__/schema-generator/json-to-schema.spec.ts
- src/custom-rules/values.ts
- src/fields/date-field/date-field.ts
- src/fields/date-field/types.ts
- src/schema-generator/types.ts
- src/shared/error-messages.ts
- src/utils/date-time-helper.ts
**Changes**
- Add `beyondDays` validation to `date-field`
- Add `beyondDays` conditional rendering
> beyondDays validation / conditional rendering

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/validation-schema-generator/wiki/Changelog#v131
> [MISC][WL] v1.3.1

- src/__tests__/fields/date-field.spec.ts
- src/schema-generator/types.ts
- src/utils/date-time-helper.ts
> Update `beyondDays` and `withinDays` validation

- src/__tests__/fields/array-field.spec.ts
- src/fields/array-field.ts
- src/fields/generate-field-configs.ts
- src/fields/types.ts
- src/schema-generator/json-to-schema.ts
- src/schema-generator/types.ts
**Changes**
- Fixes the key to use `referenceKey` instead of `uiType` to match FEE 
> Fix missing validation for FEE array-field

- src/__tests__/schema-generator/json-to-schema.spec.ts
- src/custom-rules/apply-custom-rules.ts
**Changes**
- ensure conditional rendering rule is applied for `beyondDays`
> Include `beyondDays` conditional rendering rule

- src/__tests__/custom-rules/custom-rules.spec.ts
- src/custom-rules/apply-custom-rules.ts
- src/custom-rules/equals-field.ts
- src/custom-rules/values.ts
- src/schema-generator/types.ts
**Changes**
port of https://github.com/LifeSG/web-frontend-engine/pull/380
- Add `notMatches` rule to validate if value does not match a given regex
- Add `notEqualsField` rule to validate if value does not equal another field
> Add `notMatches` and `notEqualsField` rules

- src/__tests__/fields/hidden-field.spec.ts
- src/fields/hidden-field.ts
- src/schema-generator/types.ts
**Changes**
port of https://github.com/LifeSG/web-frontend-engine/pull/379
- add value prop to hidden-field
- this will take precedence over form values and effectively force it to be uneditable
-   Set hidden-field value from schema to make the field uneditable
> Set hidden field value from schema

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/validation-schema-generator/wiki/Changelog#v133
> [MISC][WL] v1.3.3

- src/__tests__/custom-rules/custom-rules.spec.ts
- src/custom-rules/apply-custom-rules.ts
- src/custom-rules/uen.ts
- src/schema-generator/types.ts
**Changes**
Description of changes...
-  Add uen validation
-   You may refer to this [CCUBE-1776](https://sgtechstack.atlassian.net/browse/CCUBE-1776)
> [CCUBE-1776][HUY] Add Uen validation

- src/__tests__/schema-generator/yup-helper.spec.ts
- src/schema-generator/yup-helper.ts
> Fix validation failure when rule is not available on Yup schema

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/validation-schema-generator/wiki/Changelog#v134
> [MISC][WL] v1.3.4

- src/__tests__/custom-rules/custom-rules.spec.ts
- src/custom-rules/uen.ts
- src/custom-rules/uinfin.ts
**Changes**
Skip uinfin validation if empty
> [BOOKINGSG-7495][LS] Update to skip uinfin validation if it is empty

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/validation-schema-generator/wiki/Changelog#v137
> [MISC][WL] v1.3.7

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/validation-schema-generator/wiki/Changelog#v138
> [MISC][WL] v1.3.8
